# Generated by Django 4.2.20 on 2025-04-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
