# Generated by Django 4.2.20 on 2025-04-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_account'),
        ('worktimes', '0003_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktimes.worktype')),
            ],
        ),
    ]
