# Generated by Django 4.2.20 on 2025-04-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worktimes', '0005_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='special_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worktimes.specialdate'),
        ),
    ]
