# Generated by Django 4.2.20 on 2025-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Last Name')),
                ('birth_day', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], max_length=1, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=128, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('hire_date', models.DateField(blank=True, verbose_name='Hire Date')),
                ('termination_date', models.DateField(blank=True, verbose_name='Termination Date')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='Avatar'),
        ),
    ]
