# Generated by Django 4.2.20 on 2025-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termination Date'),
        ),
    ]
